export enum TableName {
  USERS = 'users',
  PROPERTIES = 'properties',
  INSPECTIONS = 'inspections',
  LEASES = 'leases',
  PROPERTY_PARTIES = 'property_parties',
  STATES = 'states',
  SIGNATURES = 'signatures',
  USER_ROLES = 'user_roles',
  ROLES = 'roles',
  REFRESH_TOKENS = 'refresh_tokens',
  PROPERTY_TYPES = 'property_types',
  NOTIFICATIONS = 'notifications',
  INSPECTION_TYPES = 'inspection_types',
  INSPECTION_SECTIONS = 'inspection_sections',
  INSPECTION_MEDIA = 'inspection_media',
  INSPECTION_ITEMS = 'inspection_items',
  CITIES = 'cities',
}